// <auto-generated />
using DeepDive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeepDive.Migrations
{
    [DbContext(typeof(EquipmentContext))]
    partial class EquipmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeepDive.Models.BCD", b =>
                {
                    b.Property<int>("BCDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BCDId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BCDId");

                    b.ToTable("BCDs");

                    b.HasData(
                        new
                        {
                            BCDId = 1,
                            Brand = "Scubapro",
                            Model = "Navigator Lite BCD",
                            Price = 125.0,
                            Size = "S, M, L"
                        },
                        new
                        {
                            BCDId = 2,
                            Brand = "Scubapro",
                            Model = "BCD Glide",
                            Price = 140.0,
                            Size = "S, M, L"
                        },
                        new
                        {
                            BCDId = 3,
                            Brand = "Scubapro",
                            Model = "BCD Hydros Pro",
                            Price = 200.0,
                            Size = "S, M, L"
                        },
                        new
                        {
                            BCDId = 4,
                            Brand = "Seac",
                            Model = "BCD Modular",
                            Price = 145.0,
                            Size = "S, M, L"
                        });
                });

            modelBuilder.Entity("DeepDive.Models.DivingSuits", b =>
                {
                    b.Property<int>("DivingSuitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivingSuitsId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thickness")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivingSuitsId");

                    b.ToTable("DivingSuits");

                    b.HasData(
                        new
                        {
                            DivingSuitsId = 1,
                            Brand = "Scubapro",
                            Gender = "Herre/Dame",
                            Model = "Definition",
                            Price = 100.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 3,
                            Type = "Våddragt"
                        },
                        new
                        {
                            DivingSuitsId = 2,
                            Brand = "Scubapro",
                            Gender = "Herre/Dame",
                            Model = "Definition",
                            Price = 100.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 5,
                            Type = "Våddragt"
                        },
                        new
                        {
                            DivingSuitsId = 3,
                            Brand = "Scubapro",
                            Gender = "Herre/Dame",
                            Model = "Definition",
                            Price = 100.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 7,
                            Type = "Våddragt"
                        },
                        new
                        {
                            DivingSuitsId = 4,
                            Brand = "Waterproof",
                            Gender = "Herre/Dame",
                            Model = "W5",
                            Price = 100.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 3,
                            Type = "Våddragt"
                        },
                        new
                        {
                            DivingSuitsId = 5,
                            Brand = "Fourth Element",
                            Gender = "Herre/Dame",
                            Model = "Proteus",
                            Price = 120.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 5,
                            Type = "Våddragt"
                        },
                        new
                        {
                            DivingSuitsId = 6,
                            Brand = "Scubapro",
                            Gender = "Herre/Dame",
                            Model = "Exodry 4.0",
                            Price = 300.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 0,
                            Type = "Tørdragt"
                        },
                        new
                        {
                            DivingSuitsId = 7,
                            Brand = "Waterproof",
                            Gender = "Herre/Dame",
                            Model = "D7 Evo",
                            Price = 320.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 0,
                            Type = "Tørdragt"
                        },
                        new
                        {
                            DivingSuitsId = 8,
                            Brand = "Santi",
                            Gender = "Herre/Dame",
                            Model = "E.Lite Plus",
                            Price = 350.0,
                            Size = "XS, S, M, L, XL",
                            Thickness = 0,
                            Type = "Tørdragt"
                        });
                });

            modelBuilder.Entity("DeepDive.Models.Finns", b =>
                {
                    b.Property<int>("FinnsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinnsId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FinnsId");

                    b.ToTable("Finns");

                    b.HasData(
                        new
                        {
                            FinnsId = 1,
                            Brand = "Scubapro",
                            Model = "Jet Fin",
                            Price = 50.0,
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            FinnsId = 2,
                            Brand = "Scubapro",
                            Model = "GO Travel",
                            Price = 50.0,
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            FinnsId = 3,
                            Brand = "Scubapro",
                            Model = "Seawing Supernova",
                            Price = 60.0,
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            FinnsId = 4,
                            Brand = "Seac",
                            Model = "Propulsion",
                            Price = 50.0,
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            FinnsId = 5,
                            Brand = "Seac",
                            Model = "ALA",
                            Price = 50.0,
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            FinnsId = 6,
                            Brand = "Fourth Element",
                            Model = "Tech",
                            Price = 75.0,
                            Size = "XS, S, M, L, XL"
                        },
                        new
                        {
                            FinnsId = 7,
                            Brand = "Fourth Element",
                            Model = "Rec Fin",
                            Price = 80.0,
                            Size = "XS, S, M, L, XL"
                        });
                });

            modelBuilder.Entity("DeepDive.Models.Mask_Snorkel", b =>
                {
                    b.Property<int>("Mask_SnorkelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mask_SnorkelId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Mask_SnorkelId");

                    b.ToTable("Mask_Snorkels");

                    b.HasData(
                        new
                        {
                            Mask_SnorkelId = 1,
                            Brand = "Scubapro",
                            Model = "Ghost",
                            Price = 50.0
                        },
                        new
                        {
                            Mask_SnorkelId = 2,
                            Brand = "Scubapro",
                            Model = "D-Mask",
                            Price = 60.0
                        },
                        new
                        {
                            Mask_SnorkelId = 3,
                            Brand = "Scubapro",
                            Model = "Spectra Mini",
                            Price = 50.0
                        },
                        new
                        {
                            Mask_SnorkelId = 4,
                            Brand = "Scubapro",
                            Model = "Crystal VU",
                            Price = 75.0
                        },
                        new
                        {
                            Mask_SnorkelId = 5,
                            Brand = "Fourth Element",
                            Model = "Scout Kontrast",
                            Price = 75.0
                        },
                        new
                        {
                            Mask_SnorkelId = 6,
                            Brand = "Fourth Element",
                            Model = "Scout Enhance",
                            Price = 75.0
                        },
                        new
                        {
                            Mask_SnorkelId = 7,
                            Brand = "Tusa",
                            Model = "Element",
                            Price = 75.0
                        });
                });

            modelBuilder.Entity("DeepDive.Models.RegulatorSet", b =>
                {
                    b.Property<int>("RegulatorSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegulatorSetId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Octopus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SecondStep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegulatorSetId");

                    b.ToTable("RegulatorSets");

                    b.HasData(
                        new
                        {
                            RegulatorSetId = 1,
                            Brand = "Scubapro",
                            FirstStep = "MK25EVO",
                            Octopus = "R105",
                            Price = 125.0,
                            SecondStep = "S600"
                        },
                        new
                        {
                            RegulatorSetId = 2,
                            Brand = "Scubapro",
                            FirstStep = "MK17EVO",
                            Octopus = "R095",
                            Price = 100.0,
                            SecondStep = "C370"
                        },
                        new
                        {
                            RegulatorSetId = 3,
                            Brand = "Scubapro",
                            FirstStep = "MK25EVO BT",
                            Octopus = "S270",
                            Price = 150.0,
                            SecondStep = "A700 Carbon BT"
                        });
                });

            modelBuilder.Entity("DeepDive.Models.Tank", b =>
                {
                    b.Property<int>("TankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TankId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Volumen")
                        .HasColumnType("int");

                    b.HasKey("TankId");

                    b.ToTable("Tanks");

                    b.HasData(
                        new
                        {
                            TankId = 1,
                            Brand = "Scubapro",
                            Price = 150.0,
                            Volumen = 5
                        },
                        new
                        {
                            TankId = 2,
                            Brand = "Scubapro",
                            Price = 160.0,
                            Volumen = 10
                        },
                        new
                        {
                            TankId = 3,
                            Brand = "Scubapro",
                            Price = 170.0,
                            Volumen = 12
                        },
                        new
                        {
                            TankId = 4,
                            Brand = "Scubapro",
                            Price = 180.0,
                            Volumen = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
