@host = https://localhost:7240
@token = CfDJ8DH3epBqgfFNmQFxfXbMvQrSttNlGkSVO4EPLkRNjRfsRHgKnfr5yO5LENUAg5rX2R9Jwy12OWlMgWgBhoBfaTNSzdmpWe1josN5CLzkIzNQsL6-mFr-8iZPIarmKijHIjp-_u0QIxNVNNLkhG1zA6oJeVPRXfWULjWgAmXWPINjsZl6UbpXlEVNFqI4sm24zE_UOL0GDfi99S-DeSVHeNe_mrkTwYktETDOv7BK9YKvuHm43CWXNMsdMxAzq0Tklk7DOB22EGKXgshxboFAiNaNxn56aMr90SuFRIgS0-CF6onES-hcfQeIqhQ7LBGCG3FvYps_HugeLvUdKGqHkvYkF4A8NNmSbZIhNSVNqlXAniEX1eX3orXpCmevYUEtO189mLukGkFitLxAtt6f8cQqDR0E8yhX-XKika3r_0woOUm0OCToWACeUy00QqQBemQVLKqQ_1PaIu5YNbgUUBoeg4GfYey5CNq36kZTl9G6WqDneAyL4svPe5yuCkqCeWH-DzcPH6rUoRtTd8X2Og_Zp2AH2nsdqnCBhSk9bSXIR3rgd0m6N98b676x_UEygpqulF_zICMD-mYph_Bg8GpiFUfwbZ8QrKcLO3yxYYd3l9aPGEeDWgfnl82KLMmM8W-6am143V02wzG-4zOREvF1eHoiBtyn7AS4vxJ8RxzT7ZRd-yWuIApxde_LGzZxnw

### 1. Register
POST {{host}}/api/account/register
Content-Type: application/json

{
  "email": "test@test.dk",
  "password": "Test123!"
}
### 2. Login (mobile - returns token)
POST {{host}}/api/account/login
Content-Type: application/json

{
  "email": "test@test.dk",
  "password": "Test123!"
}
### 3. Who am I - without token (expect 401)
GET {{host}}/claims
### 4. Who am I - with token (expect 200)
GET {{host}}/claims
Authorization: Bearer {{token}}
### My bookings with token (expect 200)
GET {{host}}/api/BookingAPI
Authorization: Bearer {{token}}