@host = https://localhost:7240
@token = CfDJ8A1QDlKCe41KvaFF446d8wdDcPu97Q2AzEzyWH-RgEiLntuaQ97nwk5J6E_b96f0XWNl0Fe3x5Y0zgJRG-Oyf4gvLTnpumGAUlsirKczpYkKuSCtCzllhpGkuZHCk5az3UVQn1k1e_fhBcX1tpMFzsRwWPjIypjxwKSxA--5qRYRrYOwzyEyfRp5GBDiA_RswH_IC-GwSFPa4JWCNHOwIsmldh4Aj-UBwQjeLu_DTT9hjgBojJC4zdqFonGa58LwfKJDJp12ZU1xtHcw6W8f8FvARS8jQzOItmvofhsQ51pASe0Khxp4_DxEBMKPH7ayKdql2zU2Kzibnzf8_isYA4Cyzx0TDKNkJmJV2vrf_p2QFgui3O9hWcAExyh6VwwlS8CAg8fgjZzThNE0AouumWX624w0OXE0JRp4YScNohdaL9XUFgvEqEm_kpbpPdyspopG8Oo-M8MC1IYR-BivZJMwnkP9GDQYuGUO-qCD_dpbOaCvHyraaeqWhvf7EUnDwm6btrjFxtx-97OOgkk6E-pWEfrGN_iXVyP5Y-q9SIXZih_j8GQpBMb6iHGch9WnBNtRsQWOcg1wfIEwV33DM90L7hycvx2las1IvARBWWdmHwHPNDcKLK8msYQxvNFnI_pXo2N0sh2vUKog1uLPp92EjN-AHED6B6Kv7uSkhbM8GQ1boHJlGi9RkwvK-GbQ8A

### 1. Register
POST {{host}}/api/account/register
Content-Type: application/json

{
  "email": "test@test.dk",
  "password": "Test123!"
}
### 2. Login (mobile - returns token)
POST {{host}}/api/account/login
Content-Type: application/json

{
  "email": "test@test.dk",
  "password": "Test123!"
}
### 3. Who am I - without token (expect 401)
GET {{host}}/claims
### 4. Who am I - with token (expect 200)
GET {{host}}/claims
Authorization: Bearer {{token}}
### My bookings with token (expect 200)
GET {{host}}/api/BookingAPI
Authorization: Bearer {{token}}